baseURL = 'http://localhost:1313/'
languageCode = 'ko-kr'
title = 'JDY 디자인 블로그'
theme = "PaperMod"

# 작성자 정보를 구조화하여 입력
[author]
    name = "JDY"

[params]
    env = "development"
    author = "JDY" # params 안에도 한 번 더 넣어줍니다.